# Generated by Django 3.2.7 on 2021-09-30 22:47

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('year', models.IntegerField(choices=[(4, 'الرابعة'), (5, 'الخامسة')])),
                ('specialty', models.CharField(choices=[('p', 'برمجيات'), ('n', 'شبكات')], max_length=20)),
                ('mark', models.IntegerField()),
                ('documentation_book', models.FileField(upload_to=projects.models.upload_book)),
                ('presentation_file', models.FileField(upload_to=projects.models.upload_presentation)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SuperVisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_visors', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=projects.models.upload_photo)),
                ('number', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project')),
            ],
        ),
    ]
