# Generated by Django 3.2.7 on 2021-10-01 00:53

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to=projects.models.upload_photo),
        ),
    ]
