# Generated by Django 3.2.7 on 2021-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='documentation_book',
            new_name='documentation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='presentation_file',
            new_name='presentation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='projectName',
        ),
        migrations.RemoveField(
            model_name='project',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='specification',
            field=models.CharField(default='tt', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='studyYear',
            field=models.CharField(default='22', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='project_supervisors', to='projects.SuperVisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='project_tools', to='projects.Technology'),
        ),
    ]
