# Generated by Django 3.2.7 on 2021-10-03 20:35

from django.db import migrations, models
import projects.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=projects.helpers.upload_thumbnail),
        ),
    ]
