export const supervisors = [
    'د. محسن حسين',
    'د. مهند رجب',
    'د. كمال سلوم',
    'د. رانيا لطفي',
    'د. ناصر ابوصالح',
    'د. اليدا اسبر',
    'د. سهيل حمود',
    'د. اسماء الشعار',
    'د. ايفا حريقص',
    'د.اكرم المرعي',
    'د.علي الحاتم',
    'د. محسن عبود',
    'د. يمان غاوي',
    'د. اسامة الناصر',
    'م. هبة التدمري',
    'م. نهلة سعد الدين',
    'م. بشرى غزالة',
    'م. مرام الخوري',
    'م. طريف كزلي',
    'م. اياد صوفان',
    'م. لارا علي'
]

export const tools = {
    "Adonis Js" : "devicon-adonisjs-original",
    "Android" :"devicon-android-plain",
    "Angular": "devicon-angularjs-plain",
    "Bootstrap" :"devicon-bootstrap-plain",
    "Bulma" : "devicon-bulma-plain",
    "C" : "devicon-c-plain",
    "Codeigniter" : "devicon-codeigniter-plain",
    "Composer" : "devicon-composer-line",
    "C++" : "devicon-cplusplus-plain",
    "C#" : "devicon-csharp-plain",
    "CSS 3":"devicon-css3-plain",
    "Dart" : "devicon-dart-plain",
    "Django" : "devicon-django-plain",
    "Dot Net" : "devicon-dot-net-plain",
    "Dot Net Core" : "devicon-dotnetcore-plain",
    "Electron JS" : "devicon-electron-original",
    "FeathersJS" : "devicon-feathersjs-original",
    "Firebase" :"devicon-firebase-plain",
    "Flask" : "devicon-flask-original",
    "Flutter" : "devicon-flutter-plain",
    "GO" : "devicon-go-plain",
    "Gradle" : "devicon-gradle-plain",
    "Gulp" : "devicon-gulp-plain",
    "HTML 5" : "evicon-html5-plain",
    "Ionic" : " devicon-ionic-original ",
    "Java" : "devicon-java-plain",
    "JavaScript" : "devicon-javascript-plain",
    "JQuery" :"devicon-jquery-plain",
    "Kotlin" : "devicon-kotlin-plain",
    "Laravel" : "devicon-laravel-plain",
    "Material UI" : "devicon-materialui-plain",
    "Mongo DB" : "devicon-mongodb-plain",
    "MySql" : "devicon-mysql-plain",
    "NextJS":"devicon-nextjs-original-wordmark",
    "NodeJS":"devicon-nodejs-plain",
    "Oracle" : "devicon-oracle-original",
    "PHP" :"devicon-php-plain",
    "Python" : "devicon-python-plain",
    "Rails":"devicon-rails-plain",
    "React JS" :"devicon-react-original",
    "Ruby":"devicon-ruby-plain",
    "Saas":"devicon-sass-original",
    "Scala":"devicon-scala-plain",
    "Socket IO" : "devicon-socketio-original",
    "Spring":"devicon-spring-plain",
    "Type Script" :"devicon-typescript-plain",
    "Vue JS" :"devicon-vuejs-plain",
    "WordPress" :"devicon-wordpress-plain",
    "Adobe XD" :"devicon-xd-plain",
}